// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/zldongly/email_server/app/admin/internal/api"
	"github.com/zldongly/email_server/app/admin/internal/conf"
	"github.com/zldongly/email_server/app/admin/internal/data"
	"github.com/zldongly/email_server/app/admin/internal/server"
	"github.com/zldongly/email_server/app/admin/internal/service"
	"github.com/zldongly/email_server/pkg/app"
	"go.uber.org/zap"
)

// Injectors from wire.go:

func initServer(confServer *conf.Server, confData *conf.Data, sugaredLogger *zap.SugaredLogger) (app.Server, func(), error) {
	client := data.NewMongo(confData, sugaredLogger)
	dataData, cleanup, err := data.NewData(client, sugaredLogger)
	if err != nil {
		return nil, nil, err
	}
	templateRepo := data.NewTemplateRepo(dataData, sugaredLogger)
	templateUseCase := service.NewTempleCase(templateRepo, sugaredLogger)
	recordRepo := data.NewRecordRepo(dataData, sugaredLogger)
	recordUseCase := service.NewRecordUseCase(recordRepo, sugaredLogger)
	admin, err := api.NewAdmin(sugaredLogger, templateUseCase, recordUseCase)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	appServer := server.NewServer(confServer, admin, sugaredLogger)
	return appServer, func() {
		cleanup()
	}, nil
}
