// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/zldongly/email_server/app/job/internal/api"
	"github.com/zldongly/email_server/app/job/internal/conf"
	"github.com/zldongly/email_server/app/job/internal/data"
	"github.com/zldongly/email_server/app/job/internal/server"
	"github.com/zldongly/email_server/app/job/internal/service"
	"github.com/zldongly/email_server/pkg/app"
	"go.uber.org/zap"
)

// Injectors from wire.go:

func initServer(cm *conf.Mail, log *zap.SugaredLogger) (app.Server, func(), error) {
	client := server.NewKafkaClient(log)
	mongoClient := data.NewMongo(log)
	dataData, cleanup, err := data.NewData(mongoClient, log)
	if err != nil {
		return nil, nil, err
	}
	emailRepo := data.NewJobRepo(dataData, log)
	mailCase := service.NewMailCase(cm, log)
	emailUseCase := service.NewEmailUseCase(emailRepo, mailCase, log)
	apiApi := api.NewJob(emailUseCase, log)
	appServer := server.NewServer(client, apiApi, log)
	return appServer, func() {
		cleanup()
	}, nil
}
