version: "3.8"
services:
  mongodb:
    image: mongo
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: admin
#      MONGO_INITDB_ROOT_PASSWORD: 123456
    ports:
    - 27017:27017
    volumes:
    - "./data/mongo/db:/data/db"
    command: mongod --auth
    tty: true

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "192.168.124.40"
      KAFKA_CREATE_TOPICS: "email:1:1"  # topic:partition:replica
      KAFKA_ZOOKEEPER_CONNECT: 192.168.124.40:2181
#      volumes:
#        - /var/run/docker.sock:/var/run/docker.sock
